### ISSUE TITLE
Install fails since last commit

### ISSUE THREAD

**Issue by wbuthod** [keflavich/imf#17]
On a hunch, I need to get the install to recognize the newly added `ah_bootstrap.py`?

    $ pip uninstall -y imf && pip install git+https://github.com/keflavich/imf.git
    Successfully uninstalled imf-0.1
    Collecting git+https://github.com/keflavich/imf.git
      Cloning https://github.com/keflavich/imf.git to /tmp/pip-req-build-07ev7scp
      Running command git clone -q https://github.com/keflavich/imf.git /tmp/pip-req-build-07ev7scp
      Installing build dependencies ... done
      Getting requirements to build wheel ... error
      ERROR: Command errored out with exit status 1:
       command: /home/wab/.pyenv/versions/3.8.2/envs/default/bin/python3.8 /home/wab/.pyenv/versions/3.8.2/envs/default/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpkc8117ei
           cwd: /tmp/pip-req-build-07ev7scp
      Complete output (16 lines):
      Traceback (most recent call last):
        File "/home/wab/.pyenv/versions/3.8.2/envs/default/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
          main()
        File "/home/wab/.pyenv/versions/3.8.2/envs/default/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/wab/.pyenv/versions/3.8.2/envs/default/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-3pmd1mt3/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 147, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "/tmp/pip-build-env-3pmd1mt3/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 128, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-3pmd1mt3/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 143, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 8, in <module>
          import ah_bootstrap
      ModuleNotFoundError: No module named 'ah_bootstrap'
      ----------------------------------------
    ERROR: Command errored out with exit status 1: /home/wab/.pyenv/versions/3.8.2/envs/default/bin/python3.8 /home/wab/.pyenv/versions/3.8.2/envs/default/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpkc8117ei Check the logs for full command output.

**Comment by keflavich** [comment]
apparently that is deprecated; I'm still trying to get the overarching package config to work...

**Comment by keflavich** [comment]
ok so the install should be cleaner now and tests work, they're just not passing on travis but they are locally..

**Comment by wbuthod** [comment]
Installed without error or warnings/
